### ISSUE TITLE
iridium.db.postgres & Android

### ISSUE THREAD

**Issue by kappesLab** [activa/iridium#4]
Is `iridium.db.postgres` compatible with MonoAndroid (Xamarin project) ?
I should access the data in a server database "PostgreSQL" from Android (mobile) and Windows (desktop) applications. Is it possible to make this driver compatible with Android, even only for reading and updating data ?

**Comment by activa** [comment]
Postgres is not supported in mobile apps (Android, iOS and UWP) at this time.

**Comment by kappesLab** [comment]
Is it possible to have this functionality in the future ? Can I help you somehow ?

**Comment by activa** [comment]
The postgres driver needs to be converted to a .NET Standard 1.3 library. It's currently a .NET Framework 4.5 library. I will see if I can make that happen.

**Comment by kappesLab** [comment]
Ok, thank you very much

**Comment by activa** [comment]
An updated nuget package for Postgres is available (2.2.0.313). It should work in any .NET Standard 1.3+ application, including Xamarin Android and iOS.

**Comment by kappesLab** [comment]
Thank you again for your quick response.
