### ISSUE TITLE
ObservableCollection<T> question

### ISSUE THREAD

**Issue by kappesLab** [activa/iridium#5]
What could be the best strategy to derive from `IDataSet<T>` an `ObservableCollection<T>` to use the binding of data with UI ?

**Comment by activa** [comment]
What's the use case you're looking for? If it's just for showing a list of records, you can simply instantiate an ObservableCollection and pass the dataset as the constructor parameter:

`new ObservableCollection<Product>(db.Products) // db.Products is of type IDataSet<Product>`

**Comment by kappesLab** [comment]
Ok, well.
