### ISSUE TITLE
Problem with reference from iridium.db.mysql.dll v2.2.0.221 to MySql.Data.dll v6.9.9.0

### ISSUE THREAD

**Issue by ghost** [activa/iridium#6]
Running application in Windows cannot load assembly MySql.Data,
"The assembly manifest definition does not match the reference to the assembly"

 'MySql.Data, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' 

nuget.org say "The owner has unlisted this package. This could mean that the package is deprecated or shouldn't be used anymore."

https://www.nuget.org/packages/mysql.data/6.9.9

The next version for MySql.Data is v6.9.12

thks

**Comment by activa** [comment]
I hate it when nuget package authors do that. I will update the iridium nuget package.

**Comment by activa** [comment]
The latest version of the Iridium packages should fix this problem
