### ISSUE TITLE
Think there's a typo in the nuget package

### ISSUE THREAD

**Issue by TheMouster** [activa/iridium#9]
I'm just trying to install 7071 in a project and I've run into this error in NuGet...

Unable to resolve dependency 'System.Data.SqlSClient'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.

Notice the "S" in System.Data.Sql**S**Client.

TIA

**Comment by TheMouster** [comment]
Line 21 of Iridium.DB.SqlServer.nuspec

**Comment by activa** [comment]
Thank you for noticing that (and fixing it!)

**Comment by TheMouster** [comment]
You‘re more than welcome.
